// "I am the Alpha and the Omega, the first and the last, the beginning and the end" (Revelation 22:13).
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { app } from "electron";
import type { PurchaseCosmeticResult, RedeemCoinCodeResult } from "../shared/types";
import { cosmeticById } from "../shared/cosmetics";
import { getOwnedCosmetics, unlockCosmetic } from "./licensing";

const WALLET_FILE = "wallet.json";

interface StoredWallet {
  coins: number;
  /** Every coin code ever redeemed, so a code can't be replayed for more coins than it was issued for. */
  redeemedCodes: string[];
}

/**
 * Replace with your own secret before shipping - same shared-client-id-style trade-off as
 * LICENSE_SECRET in licensing.ts: this ships inside the app, so it's a soft gate, not real DRM (see
 * that file's comment, and README's Monetization section). What it does stop is the specific thing
 * this feature was asked to prevent - opening wallet.json in a text editor and typing a bigger
 * `coins` number, or deleting an entry from `redeemedCodes` to replay it. `sig` below is an HMAC over
 * both fields together; any edit that doesn't come with a matching signature is detected on the next
 * read and the whole wallet resets to zero rather than trusting the tampered value.
 */
const WALLET_SECRET = "REPLACE_ME_WITH_YOUR_OWN_SECRET";

function walletFilePath(): string {
  return path.join(app.getPath("userData"), WALLET_FILE);
}

function emptyWallet(): StoredWallet {
  return { coins: 0, redeemedCodes: [] };
}

function sign(wallet: StoredWallet): string {
  // Sorted so key order in the redeemedCodes array (which carries no meaning) can't change the
  // signature - only the actual set of redeemed codes, and the coin total, are signed over.
  const payload = `${wallet.coins}:${[...wallet.redeemedCodes].sort().join(",")}`;
  return crypto.createHmac("sha256", WALLET_SECRET).update(payload).digest("hex");
}

function readWallet(): StoredWallet {
  const file = walletFilePath();
  if (!fs.existsSync(file)) return emptyWallet();
  try {
    const parsed = JSON.parse(fs.readFileSync(file, "utf-8")) as Partial<StoredWallet> & { sig?: unknown };
    const wallet: StoredWallet = {
      coins: typeof parsed.coins === "number" && Number.isFinite(parsed.coins) && parsed.coins >= 0 ? parsed.coins : 0,
      redeemedCodes: Array.isArray(parsed.redeemedCodes) ? parsed.redeemedCodes.filter((c): c is string => typeof c === "string") : [],
    };
    const sigBuf = Buffer.from(typeof parsed.sig === "string" ? parsed.sig : "", "utf-8");
    const expectedBuf = Buffer.from(sign(wallet), "utf-8");
    const valid = sigBuf.length === expectedBuf.length && crypto.timingSafeEqual(sigBuf, expectedBuf);
    return valid ? wallet : emptyWallet();
  } catch {
    return emptyWallet();
  }
}

function writeWallet(wallet: StoredWallet): void {
  const file = walletFilePath();
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, JSON.stringify({ ...wallet, sig: sign(wallet) }, null, 2), "utf-8");
}

export function getCoinBalance(): number {
  return readWallet().coins;
}

/** Format: "coins:<amount>-<16-hex-nonce>-<12-hex-hmac-suffix>", generated by scripts/generate-coin-code.cjs. */
function parseCoinCode(code: string): { amount: number; nonce: string } | null {
  const match = /^coins:([0-9]+)-([a-f0-9]{16})-([a-f0-9]{12})$/i.exec(code);
  if (!match) return null;
  const [, amountStr, nonce, suffix] = match;
  const amount = Number(amountStr);
  if (!Number.isInteger(amount) || amount <= 0) return null;

  const expected = crypto.createHmac("sha256", WALLET_SECRET).update(`${amount}:${nonce.toLowerCase()}`).digest("hex").slice(0, 12);
  const suffixBuf = Buffer.from(suffix.toLowerCase(), "utf-8");
  const expectedBuf = Buffer.from(expected, "utf-8");
  const valid = suffixBuf.length === expectedBuf.length && crypto.timingSafeEqual(suffixBuf, expectedBuf);
  return valid ? { amount, nonce: nonce.toLowerCase() } : null;
}

/** Validates a coin top-up code and, on success, credits its amount to the local balance. Rejects a code that was already redeemed. */
export function redeemCoinCode(code: string): RedeemCoinCodeResult {
  const trimmed = code.trim();
  const parsed = parseCoinCode(trimmed);
  if (!parsed) {
    return { ok: false, message: "That doesn't look like a valid coin code." };
  }

  const wallet = readWallet();
  const normalized = trimmed.toLowerCase();
  if (wallet.redeemedCodes.includes(normalized)) {
    return { ok: false, coins: wallet.coins, message: "That code has already been redeemed." };
  }

  wallet.coins += parsed.amount;
  wallet.redeemedCodes.push(normalized);
  writeWallet(wallet);
  return { ok: true, coins: wallet.coins, message: `+${parsed.amount.toLocaleString()} coins` };
}

/**
 * Spends coins to unlock a cosmetic directly from the Cosmetics page (no license key involved).
 * Balance check + deduction + unlock happen together here in the main process - the renderer only
 * ever sees the result, so it can't skip the deduction by calling licensing.unlockCosmetic directly
 * (that IPC channel takes no cosmeticId-less "just unlock it" path; equip requires prior ownership).
 */
export function purchaseCosmeticWithCoins(cosmeticId: string): PurchaseCosmeticResult {
  const cosmetic = cosmeticById(cosmeticId);
  if (!cosmetic) {
    return { ok: false, message: "Unknown cosmetic." };
  }
  if (getOwnedCosmetics().includes(cosmeticId)) {
    return { ok: false, message: "You already own that cosmetic." };
  }

  const wallet = readWallet();
  if (wallet.coins < cosmetic.coinPrice) {
    return { ok: false, coins: wallet.coins, message: "Not enough coins." };
  }

  wallet.coins -= cosmetic.coinPrice;
  writeWallet(wallet);
  unlockCosmetic(cosmeticId);
  return { ok: true, coins: wallet.coins, message: `Unlocked: ${cosmetic.name}` };
}
